// This file is auto-generated by @fn/vite.
// Do not edit this file directly.

declare module '@fn/api' {
  interface ApiRouteRegistry {
    "ai-reference": {
      post: import('@fn/api').ApiMethodContract<unknown, unknown>
      options: import('@fn/api').ApiMethodContract<unknown, unknown>
    }
    "generation-jobs": {
      get: import('@fn/api').ApiMethodContract<unknown, unknown>
      post: import('@fn/api').ApiMethodContract<unknown, unknown>
    }
    "generator-node": {
      post: import('@fn/api').ApiMethodContract<unknown, unknown>
    }
  }
}

export {}